batch_size: 12
iters: 500000

train_dataset:
  type: Dataset
  dataset_root: dataset
  train_path: dataset/train.txt
  num_classes: 6
  mode: train

  transforms:
    # - type: ResizeStepScaling
    #   min_scale_factor: 0.5
    #   max_scale_factor: 2.0
    #   scale_step_size: 0.25
    # - type: RandomPaddingCrop
    #   crop_size: [256, 256]
    # - type: RandomHorizontalFlip
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: dataset
  val_path: dataset/val.txt
  num_classes: 6
  mode: val
  transforms:
    - type: Normalize

optimizer:
  # _inherited_: False
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01

  
lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00006
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
      # weight: [0.0162295,0.24774522,0.35169965,0.01744425,0.01651262,0.13216693,0.14744214,0.07075969]
  coef: [1]

test_config:
    is_slide: True
    crop_size: [256, 256]
    stride: [256, 256]

model:
  type: SegFormer
  backbone:
    type: MixVisionTransformer_B5
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/backbone/mix_vision_transformer_b5.tar.gz
  embedding_dim: 768
  num_classes: 6

